name: build LoAT base image

on:
  # Automatically run this action on every push to `master` but only
  # if there are changes in the image directory. The image does not 
  # depend on any LoAT sources, so re-build is only necessary when 
  # the configuration of the image itself changes.
  push:
    branches: 
      - master
    paths:
      - 'docker/loat-base-image/**'

  # Also allow this action to be triggered manually via a button in 
  # the GitHub UI.
  workflow_dispatch:

# Config mainly copied from here: 
# https://github.com/marketplace/actions/build-and-push-docker-images
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          # Directory where Dockerfile is located:
          context: docker/loat-base-image
          tags: 
            # overwrite the `latest` tag which is used
            # to build the LoAT binaries:
            - ${{ secrets.DOCKERHUB_USERNAME }}/loat-base:latest            
            # but also create tag the image with the 
            # current commit sha so old images can still
            # be accessed later:
            - ${{ secrets.DOCKERHUB_USERNAME }}/loat-base:{{ github.sha }}
